version: '3'

services:
  mcp-think-tank:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      # Optional: Mount a persistent memory storage directory
      # - ./memory:/app/memory
    environment:
      - NODE_ENV=production
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
      - MCP_TRANSPORT=streamable-http
      # Add any other environment variables you need here